export const MINT_INFO_URL = 'https://launch-mint-v1-devnet.raydium.io/get/by/mints'
export const CONFIG_LIST_URL = 'https://launch-mint-v1-devnet.raydium.io/main/configs'
export const LAUNCH_KLINE_URL = 'https://launch-history-v1-devnet.raydium.io/kline'
export const TRADE_HISTORY_URL = 'https://launch-history-v1-devnet.raydium.io/trade'
export const MINT_LIST_URL = 'https://launch-mint-v1-devnet.raydium.io/get/list'
